# Test $d

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install Data::Dump
      run: |
        sudo cpan install -T Data::Dump Data::Table::Text

    - name: Array
      run: |
        perl createSlices.pl
